language: node_js

cache:
    npm: true
    directories:
        - node_modules
branches:
    except:
        - dev
    only:
        - master
script:
    - npm install

jobs:
    include:
        - stage: test
        - script: npm test