language: node_js
node_js:
  - 10.13.0

cache:
  npm: true
  directories:
    - ~/.npm

branches:
  except:
    - dev
  only:
    - master

before_script:
  - npm install -g npm@latest
  - echo fs.inotify.max_user_instances=8192
  - echo fs.inotify.max_user_watches=8192
  - echo fs.inotify.max_queued_events=8192

script:
  - npm ci
  - npx jest --ci

jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
      - npm install --save-dev expo-cli
      - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD --non-interactive
      - npx expo publish --non-interactive
